# Generated by Django 5.2 on 2025-05-01 11:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProdukPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stok", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
