# Generated by Django 5.2 on 2025-05-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_produkpost_stok_alter_produkpost_deskripsi"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkpost",
            name="kategori",
            field=models.TextField(default="Kaos", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produkpost",
            name="nama",
            field=models.CharField(max_length=100),
        ),
    ]
